pet = Pet('pomerian','rom','gold',0b1,'Dog','Soy','stanford road, Palo alto, CA',date(2016,8,19))
print(pet)
print()
pet.displayAge()
print()
print("Address is "+pet.address)
print("Owner is "+pet.owner)
pet.setOwner('Misha')
print('Change the owener to '+pet.owner)
print('\nGender: ')
pet.displayGender()


dog = Dog('pomerian','rom','gold',0b0)
print(dog)
print()
dog.setBirthday(date(2015,6,6))
dog.displayAge()
print()
dog.setColor('Brown')
print('Change the color to '+dog.color)
print()
print('Gender: ')
dog.displayGender()


puppy = Puppy('pomerian','rom','gold',12)
print(puppy)
print()
puppy.displayAge()
puppy.displayGender()